# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc3c31d4a499c7a2f1509f10ebac2c3d97e1a53ec7168cc9768ff2888f53b84eda474191a6ee9868584020439084056bb61fd132ca38f6d8742b5ba89c4b34e

test:
  secret_key_base: e26fd21af24cc48328a81e58f1f50967a4ab1c7494328065fda11720aad90eced3f10f07b363b1383fa6b10c7060431d79e135dab9b22a2fb6daad01d709666e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
